### ISSUE TITLE
bbr on bosh needs superuser for pg9.6

### ISSUE THREAD

**Issue by ramonskie** [starkandwayne/bucc-bbr-boshrelease#4]
```
        roles:
        - name: postgres
          password: ((postgres_password))
          permissions:
            - SUPERUSER
```
